const SHORT_MOVIE_DURATION = 40;

const RENDER_MOVIES_BIG_SCREEN = 12;
const RENDER_MOVIES_MIDDLE_SCREEN = 8;
const RENDER_MOVIES_SMALL_SCREEN = 5;

const MORE_MOVIES_BIG_SCREEN = 3;
const MORE_MOVIES_MIDDLE_SCREEN = 2;
const MORE_MOVIES_SMALL_SCREEN = 2;

const SCREEN_BREAKPOINT_MAX = 1191;
const SCREEN_BREAKPOINT_MIDDLE = 752;
const SCREEN_BREAKPOINT_MIN = 751;

export {
  SHORT_MOVIE_DURATION,
  RENDER_MOVIES_BIG_SCREEN,
  RENDER_MOVIES_MIDDLE_SCREEN,
  RENDER_MOVIES_SMALL_SCREEN,
  MORE_MOVIES_BIG_SCREEN,
  MORE_MOVIES_MIDDLE_SCREEN,
  MORE_MOVIES_SMALL_SCREEN,
  SCREEN_BREAKPOINT_MAX,
  SCREEN_BREAKPOINT_MIDDLE,
  SCREEN_BREAKPOINT_MIN
};
